### ISSUE TITLE
0.5.0 as image artefacts (rtsp/live)

### ISSUE THREAD

**Issue by cyl3x** [jazzfool/iced_video_player#13]
Nice work on this video player implementation. I was just about to update to 0.5 but ran into a problem:
The video playback is distorted and shows artefacts that vary depending on the stream used. Screenshots are below.

Pipeline used: `uridecodebin uri={} ! videoconvert ! videoscale ! videorate ! appsink name=iced_video caps=video/x-raw,format=RGBA,pixel-aspect-ratio=1/1`

Test rtsp stream: rtsp://62.109.19.230:554/iloveyou

<details>
  <summary>v0.5.0</summary>

![image](https://github.com/user-attachments/assets/e7333719-049e-4775-9641-a5516ec90c9d)
</details>

<details>
  <summary>v0.4.0</summary>

![image](https://github.com/user-attachments/assets/c8b517c4-9858-4854-bd0c-2aa4971f8652)
</details>

**Comment by jazzfool** [comment]
Hi, thanks!
0.5.0 switched to hardware-accelerated YUV conversion so iced_video_player now expects NV12 frame data.
Please try `format=NV12` in the pipeline instead.

**Comment by cyl3x** [comment]
Awesome, thank you for your quick reply, this solves my issue
