### ISSUE TITLE
Cannot seek with http video

### ISSUE THREAD

**Issue by Quackdoc** [jazzfool/iced_video_player#17]
With HTTP video I am having issues where the file will freeze after seeking. Here is a log. I was getting EOS issues. I forced `GST_SEEK_FLAG_SEGMENT` which fixed them, but the freezing still occurs

[iced-video.txt](https://github.com/user-attachments/files/17582597/iced-video.txt)

Local video works fine. I modified minimal.rs with `video: Video::new(&url::Url::parse("https://files.catbox.moe/3b259d.mp4").unwrap()).unwrap(),` for testing.

Upon seek, the UI's duration gets set for 0. Toggling play and pause does nothing. Enabling loop will prevent the playhead from reseting to 0 but does not stop the video player from freezing.

gst-play nor KDE's dragon player exhibit this issue.

**Comment by jazzfool** [comment]
Thanks for the detailed bug report! This should be fixed by 818df27.
