### ISSUE TITLE
Req: More flexible pipeline

### ISSUE THREAD

**Issue by Quackdoc** [jazzfool/iced_video_player#18]
As it stands, when using playbin it's severely limited in what it can do. For instance it is not possible to load auxiliary streams outside of `subfile=` which makes it impossible to use tools like `yt-dlp`. 

support for using custom pipelines would be appreciated, or in general a more modular pipeline that accepts an array of inputs and using something like uridecode. I'm not entirely sure what the optimal solution would look like as I am not too familiar with gstreamer.

**Comment by jazzfool** [comment]
This should already be possible with `Video::from_gst_pipeline` which accepts any arbitrary `Pipeline` and associated video `AppSink`.

Alternatively, if you would like to modify the existing `playbin` created by `Video::new`, you can access it with `video.pipeline()`.

**Comment by Quackdoc** [comment]
ah thanks for the info, I had missed that, thanks!
