### ISSUE TITLE
`ContentFit::Cover` and `ContentFit::None` act like `ContentFit::Fill`

### ISSUE THREAD

**Issue by mtkennerly** [jazzfool/iced_video_player#21]
I tried looking at the code and couldn't figure out why, but `ContentFit::Cover` and `ContentFit::None` stretch instead of crop:

> https://github.com/user-attachments/assets/da772eb9-5c18-44d7-8471-de6ff60fce55

In comparison, here's the Iced `ferris` example:

> https://github.com/user-attachments/assets/b98ef943-9af3-4f8f-85ec-32ee8b2b8f5d

**Comment by mtkennerly** [comment]
@jazzfool I just tried out the changes from f2aa4de527144fbf77fd838561a1d33efb46bd40, but I'm seeing a bit of weird behavior.

### `iced::ContentFit::Contain`
Doesn't `Fill` the whole width and height:

> https://github.com/user-attachments/assets/91098d4d-b8d9-4d20-9e8c-efd4030bb379

### `iced::ContentFit::Cover`
The cropping seems to work, but also doesn't `Fill` the width and height:

> https://github.com/user-attachments/assets/5bc00baf-4be5-4198-87e9-2151d6a8874c

**Comment by jazzfool** [comment]
Ah, looks like the transform includes system UI scaling. Can you confirm 2442818 fixes the issue?

**Comment by mtkennerly** [comment]
That works perfectly :D Thank you!
