### ISSUE TITLE
Add libmpv support

### ISSUE THREAD

**Issue by ALEZ-DEV** [jazzfool/iced_video_player#8]
Hey there,

First thanks for the great work you made here,
It would be cool if we can use [libmpv](https://mpv.io/manual/master/#embedding-into-other-programs-libmpv) to render the video, it will be more simple to cross plateform app between windows, linux and macos, and MPV have great built-in features that we could use directly in Iced if this would be implemented!

I made some research on my side and someone made a rust abstraction on the libmpv.c library : https://github.com/kohsine/libmpv2-rs
I don't really know if this is really feasible, because libmpv `render.rs` use OpenGL to render the video and Iced change their backend from glow to WGPU some times ago (and if I saw right, WGPU don't really support OpenGL), so tell me what you think about that!

I would be happy to help! even if my knowledge are limited in that area (I want to learn more on graphics related things)

**Comment by jazzfool** [comment]
Hi, thanks for your interest in this project.
The problem with using libmpv is, as you said, the fact that libmpv targets OpenGL, whereas Iced uses WGPU (and for which we have no way to control the backend WGPU selects without changes in Iced). So, I don't think it would be feasible to use libmpv.

Having said that, are there features you feel are missing in this library or platforms that you found don't work? In general, gstreamer supports quite a lot of features and should work across MacOS, Windows, and Linux.

**Comment by ALEZ-DEV** [comment]
This is a little example, but you could customize your experience by using custom `.glsl` shaders files
For example I have this [repo](https://github.com/bloc97/Anime4K) which upscale in realtime the video I watch.
I don't know if this would be possible too here ?
